FoodSpin.WebMVC/Models/CartViewModel.cs
using FoodSpin.Data;
using System.Collections.Generic;

namespace FoodSpin.WebMVC.Models
{
    public class CartViewModel
    {
        public List<Cart> CartProductsList { get; set; }
        public decimal CartTotalPrice { get; set; }
    }
}

FoodSpin.WebMVC/Controllers/CartController.cs
using FoodSpin.Services;
using FoodSpin.WebMVC.Models;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FoodSpin.WebMVC.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart/Index
        public ActionResult Index()
        {
            var cart = CartService.GetCart(this.HttpContext);

            var viewModel = new CartViewModel
            {
                CartProductsList = cart.GetCartProducts(),
                CartTotalPrice = cart.GetCartTotalPrice()
            };

            return View(viewModel);
        }

        // Post: Cart/AddToCart/{id}
        [HttpPost]
        public async Task<ActionResult> AddToCart(int id)
        {
            var productService = new ProductService();
            var product = await productService.GetProductByIdAsync(id);

            var cart = CartService.GetCart(this.HttpContext);

            int numberOfProductsInCart = cart.AddToCart(product);

            var model = new CartRemoveViewModel
            {
                CartTotalPrice = cart.GetCartTotalPrice(),
                CartTotalProducts = cart.GetCartTotalProducts(),
                NumberOfProductsInCart = numberOfProductsInCart,
                DeleteId = id
            };

            return Json(model);

            // return RedirectToAction("Index");
        }

        // AJAX: Cart/RemoveFromCart/{id}
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            var cart = CartService.GetCart(this.HttpContext);

            int productCount = cart.RemoveFromCart(id);

            var model = new CartRemoveViewModel
            {
                CartTotalPrice = cart.GetCartTotalPrice(),
                CartTotalProducts = cart.GetCartTotalProducts(),
                NumberOfProductsInCart = productCount,
                DeleteId = id
            };

            return Json(model);
        }

        // GET: Cart/CartStatus
        [ChildActionOnly]
        public ActionResult CartStatus()
        {
            var cart = CartService.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCartTotalProducts();

            return PartialView("CartStatus");
        }
    }
}

FoodSpin.WebMVC/Controllers/CheckoutController.cs
using FoodSpin.Data;
using FoodSpin.Services;
using System;
using System.Web.Mvc;

namespace OpenOrderFramework.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        // GET: /Checkout/Index
        public ActionResult Index()
        {
            var previousOrder = OrderService.GetPreviousOrder(this.HttpContext);
            var cart = CartService.GetCart(this.HttpContext);
            ViewBag.Cart = cart.GetCartProducts();
            ViewBag.TotalPrice = cart.GetCartTotalPrice();

            if (previousOrder != null)
            {

                return View(previousOrder);
            }
            else
            {
                return View();
            }
        }

        // POST: /Checkout/PlaceOrder
        [HttpPost]
        public ActionResult PlaceOrder(FormCollection values)
        {
            var order = new Order();
            TryUpdateModel(order);
            try
            {
                order.Username = User.Identity.Name;
                order.Email = User.Identity.Name;
                order.OrderDate = DateTime.Now;

                var cart = CartService.GetCart(this.HttpContext);
                order = cart.CreateOrder(order);

                return RedirectToAction("Complete", new { id = order.OrderId });
            }
            catch
            {
                return View(order);
            }
        }

        //
        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            bool isValid = OrderService.IsValid(id, this.HttpContext);

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

FoodSpin.WebMVC/Views/Cart/CartStatus.cshtml
<a href='@Url.Action("Index", "Cart")'><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"> </span><span id="cart-status" class="badge">@ViewData["CartCount"]</span></a>

FoodSpin.WebMVC/Views/Cart/Index.cshtml
@model FoodSpin.WebMVC.Models.CartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        $(".RemoveProduct").click(function () {
            var productToDelete = $(this).attr("data-id");
            if (productToDelete != '') {
                $.post("/Cart/RemoveFromCart", { "id": productToDelete },
                    function (data) {
                        if (data.NumberOfProductsInCart == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#product-count-' + data.DeleteId).text(data.NumberOfProductsInCart);
                        }
                        $('#cart-total').text(data.CartTotalPrice);
                        $('#cart-status').text(data.CartTotalProducts);
                    });
            }
        });
    });
</script>

<div class="container">
    <ul class="progressbar">
        <li class="active">Shopping Cart</li>
        <li>Checkout</li>
        <li>Order Completed</li>
    </ul>
</div>

@{

    if (Model.CartProductsList.Count > 0)
    {
        <div class="container">
            <table class="table">
                <caption>Shopping Cart</caption>
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var product in Model.CartProductsList)
                    {
                        <tr id="row-@product.ProductId">
                            <td>
                                @product.Product.ProductName
                            </td>
                            <td>
                                $@product.Product.ProductPrice
                            </td>
                            <td id="product-count-@product.ProductId">
                                @product.Count
                            </td>
                            <td>
                                <a href="#" class="RemoveProduct"
                                   data-id="@product.ProductId">
                                    <span>&times;</span>
                                </a>
                            </td>
                            <td>
                                $@(product.Product.ProductPrice * product.Count)
                            </td>
                        </tr>
                    }
                    <tr class="">
                        <td>
                            Total
                        </td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            $@Model.CartTotalPrice
                        </td>
                    </tr>
                </tbody>
            </table>

            <div style="float: right;">
                <button type="button" id="co-btn" style="margin: 0px 20px 0px 20px;" class="btn btn-primary " onclick="location.href='@Url.Action("Index", "Home")'">Continue Ordering</button>
                <button type="button" id="pc-btn" style="margin: 0px 20px 0px 20px;" class="btn btn-primary " onclick="location.href='@Url.Action("Index", "Checkout")'">Processed to Checkout</button>
            </div>
        </div>
    }
    else
    {
        <div class="container text-center">
            <hr />
            <h3>
                Your cart is currently empty.
            </h3>
            <p>
                Before proceeding to checkout you must add some products to your shopping cart.
            </p>
            <button type="button" class="btn btn-default btn-sm complete" onclick="location.href='@Url.Action("Index", "Home")'">Continue Ordering</button>
        </div>
    }
}